export enum LoginAlertType {
  SET_LOGIN_ALERT = 'SET_LOGIN_ALERT',
  REMOVE_LOGIN_ALERT = 'REMOVE_LOGIN_ALERT'
}

export enum AuthType {
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  REGISTER_FAIL = 'REGISTER_FAIL',
  USER_LOADED = 'USER_LOADED',
  AUTH_ERROR = 'AUTH_ERROR'
}
